# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9490dc0024fcdc9a18ddf517ba72391e"
name = "Social Link"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[extensions.theme]
handle = "sociallinks-extension"
